---
# tasks file for backend
- name: Build image and with build args
  community.docker.docker_image:
    name: "{{ imageback }}"
    build:
      path: "{{ dest_home }}/student-list/simple_api"
    source: build

- name: Create a network
  community.docker.docker_network:
    name: "{{ networkname }}"

- name: Start a container with the backend and connect to network
  docker_container:
    name:  api-projet-a
    recreate: "true"
    image: "{{ imageback }}"
    networks:
      - name: "{{ networkname }}"
    ports:
      - "5000:5000"
    volumes:
      - /home/aurelien/student-list/simple_api/student_age.json:/data/student_age.json
  tags: 
    - launch-backend